#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=iNGP-SH_env
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=01:00:00
#SBATCH --output=output/iNGP-%A.out

source $HOME/miniconda3/start1260.sh
conda activate instant_ngp_sh

(
    cd $HOME/instantNGP-SH
    SCENE="bicycle"

    python -m instant_ngp_sh.train \
        --data $HOME/mipnerf/$SCENE \
        --out out/$SCENE \
        --sh_degree 3 \
        --near 0.2 \
        --far 100.0 \
)