#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=ngpSH-train
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=01:00:00
#SBATCH --output=out/ngp-%A.out

set -euo pipefail

source $HOME/miniconda3/start1260.sh
conda activate instant_ngp_sh
export PYTHONUNBUFFERED=1

cd $HOME

SCENE="bicycle"
DATA="$HOME/mipnerf/$SCENE"
OUT="$HOME/instant_ngp_sh/out/$SCENE"
CKPT="$OUT/field.pt"

python -u -m instant_ngp_sh.train \
    --data "$DATA" \
    --out "$OUT" \
    --images_dir images_4 \
    --downscale 1 \
    --sh_degree 3 \
    --batch 16384 \
    --eval_chunk 32768 \
    --near 0.2 \
    --far 100.0

# echo ""
# echo "=== Full-dataset evaluation ==="

# python -u -m instant_ngp_sh.render \
#     --data "$DATA" \
#     --ckpt "$CKPT" \
#     --out "$OUT/render" \
#     --split train \
#     --images_dir images_4 \
#     --downscale 1
